# index:
  #  path: /
  #  controller: App\Controller\DefaultController::index
# 
api_commentaires:
    path: /api/commentaires
    controller: App\Controller\Api\CommentairesCreateController
    methods: [POST]

details_oeuvre:
    path: /oeuvres/{id}
    controller: App\Controller\OeuvresController 
    

